### PR TITLE
how the bugs for the different subcomponents

### PR DESCRIPTION
**Pull request by msherif1234**
sample output
```
#16 Developer: mmahmoud@redhat.com
  Rank Points: 329
  Number of Bugs: 7
  Number of OVNK Bugs: 0
  Number of OSDN Bugs: 3
  Number of other comp Bugs: 4
  Number of Bugs as NEW: 1
  Number of Bugs as ASSIGNED: 4
  Number of Bugs as POST: 2

```
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>

### CODE REVIEW

**Comment by dougsland** [comment]
lgtm. @flavio-fernandes PTAL

**Comment by dougsland** [comment]
@msherif1234 could you please also include baremetal sub-component?

**Comment by msherif1234** [comment]
> @msherif1234 could you please also include baremetal sub-component?

others will contain bm as well as metallb and any other components the team is working on but that is normally a relatively small set of people BM 3 and metallb 1 so not of interest to the vast majority I guess ?

**Comment by dougsland** [comment]
@msherif1234 well, would be cool to have these as too and others as "unknown" sub-component. WDYT?

**Comment by flavio-fernandes** [comment]
/lgtm
TY @msherif1234 and @dougsland !

**Comment by msherif1234** [comment]
> @msherif1234 well, would be cool to have these as too and others as "unknown" sub-component. WDYT?

BM isn't sub component and metallb to the rest of the team is unknown I am the only one from the team work on it

**Pull request merged**
